apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: ns-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app
          image: sultanlenvu/node13_pyapp:v2
          env:
            - name: DATABASE_URL
              value: postgresql://sultan:lenvu@postgres-service:5432/testbd
          ports:
            - containerPort: 80
              name: app
