apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: ns-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
        - name: app-container
          image: sultanlenvu/node13_pyapp
          ports:
            - containerPort: 5000
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_PORT
              value: "5432"
            - name: DB_NAME
              value: testdb
            - name: DB_USER
              value: sultan
            - name: DB_PASSWORD
              value: lenvu
