apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: ns-13
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: sultan
            - name: POSTGRES_PASSWORD
              value: lenvu
            - name: POSTGRES_DB
              value: testdb
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          emptyDir: {}
